# Generated by Django 3.1.6 on 2022-03-17 21:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(blank=True)),
                ('client_member_id', models.IntegerField(blank=True)),
                ('account_id', models.IntegerField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('media', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/yejiahn/Desktop/projects/mpulse/mpulse_project/project_app/folder'), upload_to='')),
            ],
            options={
                'managed': True,
                'unique_together': {('phone_number', 'client_member_id')},
            },
        ),
    ]
